# Generated by Django 4.1.7 on 2023-03-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=20, null=True),
        ),
    ]
