# Generated by Django 4.1.7 on 2023-03-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('WORK', 'Work'), ('PERSONAL', 'Personal'), ('SHOPPING', 'Shopping'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
